### ISSUE TITLE
Archivieren/entfernen

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/redaxo-in-rome#1]
@schuer sollte man das Repo vielleicht entfernen?
Es gibt nun ja -> https://github.com/FriendsOfREDAXO/redaxo-in-a-parcel

**Comment by schuer** [comment]
Ich würde es weiterhin bestehen lassen. Rome könnte – falls es denn jemals fertig wird – sehr nett werden und ganz viele Anwendungsfälle in einer Software vereinen. Das wäre für REDAXO interessant, weil man damit womöglich schlichte und verständliche Workflows bauen könnte.
